"""Reference calculator for implementation-capacity-and-org-design (R2).

Deterministic. No network, no clock, no randomness, no language model. The same inputs
always produce byte-identical outputs. Every calculated number in data/synthetic/,
reports/executive-pack/ (the five reports), and the generated verification documents is
written by this file; nothing calculated is typed by hand.

Inputs (read only):
  config/*.yaml, profiles/*.yaml                      parameters, rules, curves, drivers
  data/synthetic/universe.yaml                        hand-authored synthetic inputs
  upstream/r3/exports/csv/capacity-inputs.csv         pinned R3 Capacity Inputs (bottom-up)
  upstream/r1/...                                     pinned R1 projects, tasks, standard

Usage:
  python tools/capacity_calc.py            regenerate every output
  python tools/capacity_calc.py --check    exit 1 if any committed output differs
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import hashlib
import io
import json
import math
import sys
from collections import defaultdict
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CALCULATION_VERSION = "0.1.0"
SCHEMA_VERSION = "0.1.0"
REPO = "implementation-capacity-and-org-design"
R3_REPO = "implementation-tracker-workbook"
METHODS = ("bottom_up", "top_down")
INCLUSION = ("authoritative_workload", "informational_only", "excluded_to_prevent_double_count")
SYNTHETIC_FOOTER = "All figures in this file are synthetic data, generated by `tools/capacity_calc.py` from `data/synthetic/universe.yaml` and the pinned R3 Capacity Inputs. They are an illustrative example, not a measured result, and describe no real team."

D = Decimal


# --------------------------------------------------------------------------------------
# Number and period helpers
# --------------------------------------------------------------------------------------

def dec(x) -> Decimal | None:
    if x is None or x == "":
        return None
    return x if isinstance(x, Decimal) else D(str(x))


def q(x: Decimal, places: int) -> Decimal:
    return x.quantize(D(1).scaleb(-places), rounding=ROUND_HALF_UP)


def fmt(x) -> str:
    """Canonical text for a number: no exponent, no trailing zeros."""
    if x is None:
        return ""
    if isinstance(x, bool):
        return "true" if x else "false"
    if isinstance(x, int):
        return str(x)
    x = dec(x)
    if x == x.to_integral_value():
        return str(int(x))
    return format(x.normalize(), "f")


def jnum(x):
    """A number for JSON: int when whole, else float of the canonical text."""
    if x is None:
        return None
    if isinstance(x, int):
        return x
    s = fmt(x)
    return int(s) if "." not in s else float(s)


def period_index(p: str) -> int:
    y, m = p.split("-")
    return int(y) * 12 + int(m) - 1


def period_of(i: int) -> str:
    return f"{i // 12:04d}-{i % 12 + 1:02d}"


def add_months(p: str, n: int) -> str:
    return period_of(period_index(p) + n)


def periods_between(start: str, end: str) -> list[str]:
    return [period_of(i) for i in range(period_index(start), period_index(end) + 1)]


def first_day(p: str) -> dt.date:
    y, m = p.split("-")
    return dt.date(int(y), int(m), 1)


def sha256_text(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


# --------------------------------------------------------------------------------------
# Formulas (pure functions; tests and the validator call these directly)
# --------------------------------------------------------------------------------------

def gross_available_hours(scheduled, unavailable) -> Decimal:
    return dec(scheduled) - dec(unavailable)


def supply_breakdown(scheduled, unavailable=0, non_project=0, training=0, other=0, ramp_factor=1, mentor=0, places=2) -> dict:
    """One person, one role, one period. Raises ValueError instead of clipping."""
    vals = {k: dec(v) for k, v in dict(scheduled=scheduled, unavailable=unavailable, non_project=non_project,
                                        training=training, other=other, mentor=mentor).items()}
    rf = dec(ramp_factor)
    if any(v < 0 for v in vals.values()):
        raise ValueError("supply hour fields must be non-negative")
    if rf < 0 or rf > 1:
        raise ValueError("ramp_factor must be between 0 and 1")
    gross = gross_available_hours(vals["scheduled"], vals["unavailable"])
    project_available = gross - vals["non_project"] - vals["training"] - vals["other"]
    if gross < 0 or project_available < 0:
        raise ValueError("allowances exceed scheduled hours")
    ramp_adjusted = q(project_available * rf, places)
    ramp_loss = project_available - ramp_adjusted
    effective = ramp_adjusted - vals["mentor"]
    if effective < 0:
        raise ValueError("effective_capacity_hours would be negative")
    return {"gross_available_hours": gross, "project_available_hours": project_available,
            "ramp_adjusted_hours": ramp_adjusted, "ramp_loss_hours": ramp_loss, "effective_capacity_hours": effective}


def capacity_gap_hours(demand, supply) -> Decimal:
    """Shared standard 1.0.0: demand minus capacity. Positive means more work than capacity."""
    return dec(demand) - dec(supply)


def load_ratio(demand, supply, places=4) -> tuple[Decimal | None, str]:
    """demand / supply. Zero supply never divides and never becomes zero."""
    demand, supply = dec(demand), dec(supply)
    if supply == 0:
        return None, "undefined_no_capacity"
    return q(demand / supply, places), "defined"


def training_capacity(learner_count, class_size, track_hours, session_length_hours, prep_hours_per_session,
                      assessment_hours_per_cohort=0, places=2) -> dict:
    learners, size = int(learner_count), int(class_size)
    track, session = dec(track_hours), dec(session_length_hours)
    prep, assess = dec(prep_hours_per_session), dec(assessment_hours_per_cohort or 0)
    if learners < 0 or size <= 0 or track <= 0 or session <= 0 or prep < 0 or assess < 0:
        raise ValueError("invalid training input")
    cohorts = math.ceil(learners / size) if learners else 0
    per_cohort = math.ceil(track / session)
    sessions = cohorts * per_cohort
    delivery = q(cohorts * track, places)
    preparation = q(sessions * prep, places)
    assessment = q(cohorts * assess, places)
    return {"cohorts_required": cohorts, "sessions_per_cohort": per_cohort, "sessions_required": sessions,
            "trainer_delivery_hours": delivery, "trainer_preparation_hours": preparation,
            "trainer_assessment_hours": assessment, "trainer_hours": delivery + preparation + assessment,
            "learner_seat_hours": q(learners * track, places)}


def top_down_hours(effort_hours, effort_share, duration_months, places=2) -> Decimal:
    """Forecast hours for one role in one month of a curve segment: the tier's effort for the
    role times the segment's share, spread evenly across the segment's months."""
    if int(duration_months) < 1 or dec(effort_hours) < 0 or not (0 <= dec(effort_share) <= 1):
        raise ValueError("invalid top-down input")
    return q(dec(effort_hours) * dec(effort_share) / int(duration_months), places)


def golive_support_hours(people_count, hours_per_person_per_day, days, places=2) -> Decimal:
    if int(people_count) < 0 or dec(hours_per_person_per_day) < 0 or dec(days) < 0:
        raise ValueError("invalid launch-support input")
    return q(int(people_count) * dec(hours_per_person_per_day) * dec(days), places)


def latest_staffing_start_date(projected_gap_date: dt.date, hiring_lead_time_days: int, ramp_duration_days: int) -> dt.date:
    return projected_gap_date - dt.timedelta(days=int(hiring_lead_time_days)) - dt.timedelta(days=int(ramp_duration_days))


def evaluate_trigger(above: list[bool], below: list[bool], fire_after: int, clear_after: int) -> list[dict]:
    """Persistence and hysteresis for one rule over consecutive periods.

    Returns one dict per period: state (not_triggered, watch, triggered, clearing) and
    event (fired, cleared, or None). A period that is neither above nor below keeps a
    triggered rule triggered and resets the clearing count; before firing it resets the
    firing count.
    """
    out, state, up, down = [], "not_triggered", 0, 0
    for a, b in zip(above, below):
        event = None
        if state in ("not_triggered", "watch"):
            up = up + 1 if a else 0
            if a and up >= fire_after:
                state, event, down = "triggered", "fired", 0
            else:
                state = "watch" if a else "not_triggered"
        else:
            down = down + 1 if b else 0
            if b and down >= clear_after:
                state, event, up = "not_triggered", "cleared", 0
            else:
                state = "clearing" if b else "triggered"
        out.append({"state": state, "event": event})
    return out


def curve_rows(curve: dict) -> list[dict]:
    """Expand a curve into month offsets with the share for each month."""
    rows, offset = [], 0
    for seg in curve["segments"]:
        months = int(seg["duration_months"])
        for _ in range(months):
            rows.append({"month_offset": offset, "phase_keys": list(seg["phase_keys"]),
                         "effort_share": dec(seg["effort_share"]), "duration_months": months})
            offset += 1
    return rows


def double_count_problems(records: list[dict]) -> list[str]:
    """Authoritative-workload rules for demand records (dicts with the CSV field names)."""
    problems = []
    methods, components = defaultdict(set), defaultdict(list)
    for r in records:
        if r["capacity_inclusion_method"] not in INCLUSION:
            problems.append(f"{r['demand_record_id']}: unknown capacity_inclusion_method")
        if r["demand_method"] not in METHODS:
            problems.append(f"{r['demand_record_id']}: unknown demand_method")
        if r["capacity_inclusion_method"] != "authoritative_workload":
            if not r.get("exclusion_reason"):
                problems.append(f"{r['demand_record_id']}: non-authoritative record without exclusion_reason")
            continue
        methods[(r["project_id"], r["period"])].add(r["demand_method"])
        components[(r["workload_component_id"], r["period"])].append(r["demand_record_id"])
    for (project, period), ms in sorted(methods.items()):
        if len(ms) > 1:
            problems.append(f"{project} {period}: authoritative demand from more than one method ({', '.join(sorted(ms))})")
    for (comp, period), ids in sorted(components.items()):
        if len(ids) > 1:
            problems.append(f"{comp} {period}: authoritative more than once ({', '.join(ids)})")
    return problems


# --------------------------------------------------------------------------------------
# Loading
# --------------------------------------------------------------------------------------

def load_yaml(root: Path, rel: str):
    return yaml.safe_load((root / rel).read_text(encoding="utf-8"))


def read_csv_rows(path: Path) -> list[dict]:
    with path.open(encoding="utf-8", newline="") as h:
        return list(csv.DictReader(h))


CONFIG_FILES = ("config/parameters.yaml", "config/demand-drivers.yaml", "config/supply-rules.yaml",
                "config/phase-effort-curves.yaml", "config/staffing-triggers.yaml", "config/training-capacity.yaml",
                "config/golive-support.yaml", "profiles/startup.yaml", "profiles/early-scale.yaml",
                "profiles/structured-growth.yaml", "profiles/mature.yaml")


def config_digest(root: Path) -> str:
    h = hashlib.sha256()
    for rel in CONFIG_FILES:
        h.update(rel.encode("utf-8") + b"\n")
        h.update((root / rel).read_bytes().replace(b"\r\n", b"\n"))
    return h.hexdigest()


def load_inputs(root: Path = ROOT) -> dict:
    params = {p["parameter_id"]: p["value"] for p in load_yaml(root, "config/parameters.yaml")["parameters"]}
    profiles = {}
    for name in ("startup", "early-scale", "structured-growth", "mature"):
        prof = load_yaml(root, f"profiles/{name}.yaml")
        profiles[prof["org_profile_id"]] = prof
    return {
        "root": root,
        "params": params,
        "curves": {c["curve_id"]: c for c in load_yaml(root, "config/phase-effort-curves.yaml")["curves"]},
        "tiers": {t["tier_key"]: t for t in load_yaml(root, "config/demand-drivers.yaml")["tiers"]},
        "triggers": load_yaml(root, "config/staffing-triggers.yaml"),
        "profiles": profiles,
        "universe": load_yaml(root, "data/synthetic/universe.yaml"),
        "r3": read_csv_rows(root / "upstream/r3/exports/csv/capacity-inputs.csv"),
        "r1_projects": {r["project_id"]: r for r in read_csv_rows(root / "upstream/r1/data/synthetic/projects.csv")},
        "r1_tasks": {r["task_id"]: r for r in read_csv_rows(root / "upstream/r1/data/synthetic/tasks.csv")},
        "standard": load_yaml(root, "standard/standard-reference.yaml"),
        "config_digest": config_digest(root),
    }


# --------------------------------------------------------------------------------------
# Model
# --------------------------------------------------------------------------------------

def compute(inp: dict) -> dict:
    P, U = inp["params"], inp["universe"]
    hp, rp = int(P["hours_decimal_places"]), int(P["ratio_decimal_places"])
    horizon = periods_between(P["planning_horizon_start"], P["planning_horizon_end"])
    in_horizon = set(horizon)
    as_of = P["calculation_as_of_at"]
    std_version = str(inp["standard"]["shared_standard_version"])
    source_version = f"r3-{inp['standard']['r3_commit'][:7]}+universe-{U['version']}"
    scenarios = {s["scenario_id"]: s for s in U["scenarios"]}
    projects = {p["project_id"]: p for p in U["projects"]}
    stage_of = {sid: s["org_stage"] for sid, s in scenarios.items()}

    # ---- Demand records: bottom-up from R3, then top-down from tier curves -----------
    demand: list[dict] = []
    skipped_outside_horizon = []
    for r in inp["r3"]:
        if r["period"] not in in_horizon:
            skipped_outside_horizon.append(r["capacity_input_id"])
            continue
        proj = projects[r["project_id"]]
        if stage_of[proj["scenario_id"]] != r["org_stage"]:
            raise ValueError(f"{r['capacity_input_id']}: R3 org_stage differs from the scenario's selected stage")
        method = r["capacity_inclusion_method"]
        reason = {"informational_only": "R3 marks this row informational_only; it is context, never demand",
                  "excluded_to_prevent_double_count": f"R3 marks this row excluded; component {r['workload_component_id']} is counted by its authoritative row"}.get(method, "")
        demand.append({
            "scenario_id": proj["scenario_id"], "project_id": r["project_id"], "period": r["period"], "role_id": r["role_id"],
            "workload_component_id": r["workload_component_id"], "workload_type": r["workload_type"], "demand_method": "bottom_up",
            "source_entity_type": r["source_entity_type"], "source_entity_id": r["source_entity_id"],
            "source_repo": r["source_repo"], "source_version": r["source_version"],
            "import_source_repo": R3_REPO, "import_record_id": r["capacity_input_id"],
            "capacity_inclusion_method": method, "precedence_rank": 1,
            "hours": dec(r["planned_hours"]), "actual_hours": dec(r["actual_hours"]), "unit": "hours", "value_basis": "planned",
            "complexity_tier": proj["complexity_tier"], "curve_id": "", "month_offset": None, "phase_keys": "",
            "exclusion_reason": reason})
    bottom_up_keys = {(d["project_id"], d["period"]) for d in demand if d["capacity_inclusion_method"] == "authoritative_workload"}
    top_down = []
    for proj in U["projects"]:
        tier = inp["tiers"][proj["complexity_tier"]]
        curve = inp["curves"][tier["curve_id"]]
        for cr in curve_rows(curve):
            period = add_months(proj["curve_start_period"], cr["month_offset"])
            if period not in in_horizon:
                continue
            for role_id in sorted(tier["effort_hours_by_role"]):
                hours = top_down_hours(tier["effort_hours_by_role"][role_id], cr["effort_share"], cr["duration_months"], hp)
                covered = (proj["project_id"], period) in bottom_up_keys
                top_down.append({
                    "scenario_id": proj["scenario_id"], "project_id": proj["project_id"], "period": period, "role_id": role_id,
                    "workload_component_id": None, "workload_type": "forecast_project_effort", "demand_method": "top_down",
                    "source_entity_type": "project", "source_entity_id": proj["project_id"],
                    "source_repo": REPO, "source_version": f"demand-drivers-{load_yaml(inp['root'], 'config/demand-drivers.yaml')['version']}",
                    "import_source_repo": "", "import_record_id": "",
                    "capacity_inclusion_method": "excluded_to_prevent_double_count" if covered else "authoritative_workload",
                    "precedence_rank": 3, "hours": hours, "actual_hours": None, "unit": "hours", "value_basis": "forecast",
                    "complexity_tier": proj["complexity_tier"], "curve_id": tier["curve_id"], "month_offset": cr["month_offset"],
                    "phase_keys": "+".join(cr["phase_keys"]),
                    "exclusion_reason": "bottom_up authoritative workload exists for this project and period (precedence rank 1 wins)" if covered else ""})
    top_down.sort(key=lambda d: (d["project_id"], d["period"], d["role_id"]))
    demand += top_down
    for i, d in enumerate(demand, 1):
        d["demand_record_id"] = f"DMN-{i:06d}"
        if d["workload_component_id"] is None:
            d["workload_component_id"] = d["demand_record_id"]
        d["schema_version"] = SCHEMA_VERSION
    problems = double_count_problems(demand)
    if problems:
        raise ValueError("double counting: " + "; ".join(problems))

    # ---- Training ---------------------------------------------------------------------
    training_demand, training_cap = [], []
    for i, t in enumerate(U["training_demand"], 1):
        td = dict(t)
        td["unit_learners"] = "learners"
        training_demand.append(td)
        size = t["class_size"] if t["class_size"] is not None else P["default_class_size"]
        sess = t["session_length_hours"] if t["session_length_hours"] is not None else P["default_session_length_hours"]
        prep = t["prep_hours_per_session"] if t["prep_hours_per_session"] is not None else P["default_prep_hours_per_session"]
        calc = training_capacity(t["learner_count"], size, t["track_hours"], sess, prep, t["assessment_hours_per_cohort"], hp)
        training_cap.append({
            "training_capacity_id": f"TRC-{i:06d}", "training_demand_id": t["training_demand_id"], "scenario_id": t["scenario_id"],
            "project_id": t["project_id"] or "", "period": t["period"], "trainer_role_id": t["trainer_role_id"],
            "learner_count": int(t["learner_count"]), "class_size": int(size),
            "class_size_source": "record" if t["class_size"] is not None else "default_parameter",
            "track_hours": dec(t["track_hours"]), "session_length_hours": dec(sess),
            "session_length_source": "record" if t["session_length_hours"] is not None else "default_parameter",
            "prep_hours_per_session": dec(prep),
            "prep_source": "record" if t["prep_hours_per_session"] is not None else "default_parameter",
            "assessment_hours_per_cohort": dec(t["assessment_hours_per_cohort"] or 0),
            **calc, "capacity_inclusion_method": t["capacity_inclusion_method"], "covered_by": t.get("covered_by") or "",
            "precedence_rank": 2, "schema_version": SCHEMA_VERSION})

    # ---- Launch support ---------------------------------------------------------------
    golive = []
    for g in U["golive_support"]:
        golive.append({**g, "support_hours": golive_support_hours(g["people_count"], g["hours_per_person_per_day"], g["days"], hp),
                       "capacity_inclusion_method": g.get("capacity_inclusion_method", "authoritative_workload"),
                       "value_basis": "forecast", "precedence_rank": 2, "schema_version": SCHEMA_VERSION})

    # ---- Supply -----------------------------------------------------------------------
    supply = []
    for person in U["people"]:
        start = person.get("first_period", horizon[0])
        for alloc in person["allocations"]:
            for period in horizon:
                if period_index(period) < period_index(start):
                    continue
                rec = {"unavailable_hours": 0, "non_project_hours": alloc["non_project_hours"], "training_hours": 0,
                       "other_capacity_reduction_hours": 0, "ramp_factor": 1, "mentor_hours": 0,
                       "mentor_person_id": "", "mentee_person_id": "", "notes": []}
                for o in person.get("overrides", []):
                    if o["period"] == period and o["role_id"] == alloc["role_id"]:
                        rec[o["field"]] = o["value"]
                        if o.get("mentee"):
                            rec["mentee_person_id"] = o["mentee"]
                        if o.get("mentor"):
                            rec["mentor_person_id"] = o["mentor"]
                        if o.get("reason"):
                            rec["notes"].append(o["reason"])
                b = supply_breakdown(alloc["scheduled_work_hours"], rec["unavailable_hours"], rec["non_project_hours"],
                                     rec["training_hours"], rec["other_capacity_reduction_hours"], rec["ramp_factor"],
                                     rec["mentor_hours"], hp)
                supply.append({
                    "scenario_id": person["scenario_id"], "person_id": person["person_id"], "role_id": alloc["role_id"], "period": period,
                    "scheduled_work_hours": dec(alloc["scheduled_work_hours"]), "unavailable_hours": dec(rec["unavailable_hours"]),
                    "gross_available_hours": b["gross_available_hours"], "non_project_hours": dec(rec["non_project_hours"]),
                    "training_hours": dec(rec["training_hours"]), "other_capacity_reduction_hours": dec(rec["other_capacity_reduction_hours"]),
                    "project_available_hours": b["project_available_hours"], "ramp_factor": dec(rec["ramp_factor"]),
                    "ramp_adjusted_hours": b["ramp_adjusted_hours"], "ramp_loss_hours": b["ramp_loss_hours"],
                    "mentor_hours": dec(rec["mentor_hours"]), "effective_capacity_hours": b["effective_capacity_hours"],
                    "mentor_person_id": rec["mentor_person_id"], "mentee_person_id": rec["mentee_person_id"],
                    "ramp_source": "r4_interface_fixture" if dec(rec["ramp_factor"]) < 1 else "fully_ramped_default",
                    "value_basis": "forecast", "unit": "hours", "notes": "; ".join(rec["notes"])})
    supply.sort(key=lambda s: (s["scenario_id"], s["person_id"], s["role_id"], s["period"]))
    for i, s in enumerate(supply, 1):
        s["supply_record_id"] = f"SUP-{i:06d}"
        s["schema_version"] = SCHEMA_VERSION

    # ---- Grid: scenario x role x period ------------------------------------------------
    roles_by_scenario = defaultdict(set)
    for s in supply:
        roles_by_scenario[s["scenario_id"]].add(s["role_id"])
    for d in demand:
        if d["capacity_inclusion_method"] == "authoritative_workload":
            roles_by_scenario[d["scenario_id"]].add(d["role_id"])
    for t in training_cap:
        if t["capacity_inclusion_method"] == "authoritative_workload":
            roles_by_scenario[t["scenario_id"]].add(t["trainer_role_id"])
    for g in golive:
        roles_by_scenario[g["scenario_id"]].add(g["role_id"])
    grid = [(sid, rid, p) for sid in sorted(roles_by_scenario) for rid in sorted(roles_by_scenario[sid]) for p in horizon]

    role_capacity, snapshots = [], []
    by_key_supply = defaultdict(list)
    for s in supply:
        by_key_supply[(s["scenario_id"], s["role_id"], s["period"])].append(s)
    by_key_demand = defaultdict(list)
    for d in demand:
        if d["capacity_inclusion_method"] == "authoritative_workload":
            by_key_demand[(d["scenario_id"], d["role_id"], d["period"])].append(d)
    by_key_training = defaultdict(list)
    for t in training_cap:
        if t["capacity_inclusion_method"] == "authoritative_workload":
            by_key_training[(t["scenario_id"], t["trainer_role_id"], t["period"])].append(t)
    by_key_golive = defaultdict(list)
    for g in golive:
        if g["capacity_inclusion_method"] == "authoritative_workload":
            by_key_golive[(g["scenario_id"], g["role_id"], g["period"])].append(g)

    fields_sum = ("scheduled_work_hours", "unavailable_hours", "gross_available_hours", "non_project_hours", "training_hours",
                  "other_capacity_reduction_hours", "project_available_hours", "ramp_loss_hours", "mentor_hours", "effective_capacity_hours")
    for i, (sid, rid, period) in enumerate(grid, 1):
        sups = by_key_supply[(sid, rid, period)]
        rc = {"role_capacity_id": f"RCP-{i:06d}", "scenario_id": sid, "role_id": rid, "period": period,
              "person_count": len({s["person_id"] for s in sups})}
        for f in fields_sum:
            rc[f] = sum((s[f] for s in sups), D(0))
        rc["supply_record_ids"] = ";".join(s["supply_record_id"] for s in sups)
        rc["schema_version"] = SCHEMA_VERSION
        role_capacity.append(rc)

        dems, trs, gls = by_key_demand[(sid, rid, period)], by_key_training[(sid, rid, period)], by_key_golive[(sid, rid, period)]
        project_h = sum((d["hours"] for d in dems), D(0))
        training_h = sum((t["trainer_hours"] for t in trs), D(0))
        golive_h = sum((g["support_hours"] for g in gls), D(0))
        demand_h = project_h + training_h + golive_h
        supply_h = rc["effective_capacity_hours"]
        ratio, ratio_state = load_ratio(demand_h, supply_h, rp)
        active = sorted({d["project_id"] for d in dems if d["hours"] > 0} | {t["project_id"] for t in trs if t["project_id"]}
                        | {g["project_id"] for g in gls if g["project_id"]})
        tiers = [projects[p]["complexity_tier"] for p in active]
        profile = inp["profiles"][scenarios[sid]["org_profile_id"]]
        max_active = int(profile["planning_settings"]["max_active_projects_per_role"])
        digest_src = {
            "demand_records": [[d["demand_record_id"], fmt(d["hours"])] for d in dems],
            "training_capacity": [[t["training_capacity_id"], fmt(t["trainer_hours"])] for t in trs],
            "golive_support": [[g["golive_support_demand_id"], fmt(g["support_hours"])] for g in gls],
            "supply_records": [[s["supply_record_id"], fmt(s["effective_capacity_hours"])] for s in sups],
            "config_digest": inp["config_digest"], "calculation_version": CALCULATION_VERSION, "standard_version": std_version}
        snapshots.append({
            "capacity_snapshot_id": f"CAP-{i:06d}", "scenario_id": sid, "org_stage": scenarios[sid]["org_stage"], "role_id": rid,
            "period": period, "role_capacity_id": rc["role_capacity_id"],
            "project_demand_hours": project_h, "training_demand_hours": training_h, "golive_support_hours": golive_h,
            "demand_hours": demand_h, "effective_capacity_hours": supply_h, "capacity_gap_hours": capacity_gap_hours(demand_h, supply_h),
            "load_ratio": ratio, "load_ratio_state": ratio_state, "active_project_count": len(active),
            "active_simple_count": tiers.count("simple"), "active_standard_count": tiers.count("standard"),
            "active_complex_count": tiers.count("complex"), "max_active_projects_per_role": max_active,
            "concurrency_state": "above_configured_maximum" if len(active) > max_active else "within_configured_maximum",
            "active_project_ids": ";".join(active),
            "value_basis": "forecast", "source_version": source_version, "config_digest": inp["config_digest"],
            "inputs_digest": sha256_text(json.dumps(digest_src, sort_keys=True, separators=(",", ":"))),
            "calculation_version": CALCULATION_VERSION, "calculated_at": as_of, "standard_version": std_version,
            "schema_version": SCHEMA_VERSION, "_digest_src": digest_src})

    # ---- Triggers -----------------------------------------------------------------------
    rules = {t["staffing_trigger_id"]: t for t in inp["triggers"]["triggers"]}
    upper, lower = dec(P["load_ratio_upper_threshold"]), dec(P["load_ratio_lower_threshold"])
    series = defaultdict(list)
    for s in snapshots:
        series[(s["scenario_id"], s["role_id"])].append(s)
    fires = []
    for key in sorted(series):
        snaps = series[key]
        load_above = [s["load_ratio_state"] == "defined" and s["load_ratio"] >= upper for s in snaps]
        load_below = [(s["load_ratio_state"] == "defined" and s["load_ratio"] <= lower) or s["demand_hours"] == 0 for s in snaps]
        cov_above = [s["load_ratio_state"] == "undefined_no_capacity" and s["demand_hours"] > 0 for s in snaps]
        cov_below = [s["effective_capacity_hours"] > 0 or s["demand_hours"] == 0 for s in snaps]
        results = {
            "STG-000001": evaluate_trigger(load_above, load_below, int(P[rules["STG-000001"]["fire_after_parameter"]]), int(P[rules["STG-000001"]["clear_after_parameter"]])),
            "STG-000002": evaluate_trigger(cov_above, cov_below, int(P[rules["STG-000002"]["fire_after_parameter"]]), int(P[rules["STG-000002"]["clear_after_parameter"]])),
        }
        precedence = inp["triggers"]["combined_state_precedence"]
        for idx, s in enumerate(snaps):
            s["load_trigger_state"] = results["STG-000001"][idx]["state"]
            s["coverage_trigger_state"] = results["STG-000002"][idx]["state"]
            s["trigger_state"] = min((s["load_trigger_state"], s["coverage_trigger_state"]), key=precedence.index)
            s["active_trigger_ids"] = ";".join(r for r in ("STG-000001", "STG-000002") if results[r][idx]["state"] in ("triggered", "clearing"))
            s["trigger_events"] = ";".join(f"{r}:{results[r][idx]['event']}" for r in ("STG-000001", "STG-000002") if results[r][idx]["event"])
            for rule_id in ("STG-000001", "STG-000002"):
                if results[rule_id][idx]["event"] == "fired":
                    above = load_above if rule_id == "STG-000001" else cov_above
                    first = idx
                    while first > 0 and above[first - 1]:
                        first -= 1
                    fires.append({"rule_id": rule_id, "snapshot": s, "streak": snaps[first:idx + 1]})

    # ---- Staffing recommendations -------------------------------------------------------
    rec_types = {r["type"]: r["content"] for r in inp["triggers"]["recommendation_types"]}
    as_of_date = dt.date.fromisoformat(as_of[:10])
    lead, ramp = int(P["hiring_lead_time_days"]), int(P["ramp_duration_days"])
    recommendations = []
    for i, f in enumerate(fires, 1):
        rule = rules[f["rule_id"]]
        snap = f["snapshot"]
        gap_period = f["streak"][0]["period"]
        gap_date = first_day(gap_period)
        latest = latest_staffing_start_date(gap_date, lead, ramp)
        timing = "window_open" if latest >= as_of_date else "window_passed"
        rtype = rule["recommendation_type"]
        content = (f"{rec_types[rtype]} Signal: {rule['name']} fired in {snap['period']} for {snap['role_id']} "
                   f"({snap['scenario_id']}); first affected period {gap_period}. Planning timing under the configured "
                   f"assumptions: latest staffing start {latest.isoformat()} ({gap_date.isoformat()} minus {lead} hiring lead-time "
                   f"days minus {ramp} ramp days), {timing.replace('_', ' ')} as of {as_of_date.isoformat()}. "
                   "This is planning logic only; a named person decides what, if anything, to do.")
        refs = [{"source_type": "capacity_snapshot", "source_id": s["capacity_snapshot_id"]} for s in f["streak"]]
        refs.append({"source_type": "staffing_trigger", "source_id": f["rule_id"]})
        recommendations.append({
            "staffing_recommendation_id": f"STR-{i:06d}", "recommendation_type": rtype, "subject_type": "capacity_snapshot",
            "subject_id": snap["capacity_snapshot_id"], "content": content, "source_references": refs, "status": "proposed",
            "created_at": as_of, "origin_type": "system", "origin_id": f["rule_id"],
            "staffing_trigger_id": f["rule_id"], "scenario_id": snap["scenario_id"], "role_id": snap["role_id"],
            "fired_period": snap["period"], "first_affected_period": gap_period, "capacity_gap_hours": snap["capacity_gap_hours"],
            "projected_gap_date": gap_date.isoformat(), "hiring_lead_time_days": lead, "ramp_duration_days": ramp,
            "latest_staffing_start_date": latest.isoformat(), "timing_state": timing,
            "decision_owner": "named_human", "schema_version": SCHEMA_VERSION})

    # ---- Project ledger (one authoritative method per project and period) ---------------
    project_rows = []
    for proj in U["projects"]:
        r1 = inp["r1_projects"].get(proj["project_id"])
        tier = inp["tiers"][proj["complexity_tier"]]
        curve_periods = {add_months(proj["curve_start_period"], cr["month_offset"]): cr for cr in curve_rows(inp["curves"][tier["curve_id"]])}
        for period in horizon:
            auth = {d["demand_method"] for d in demand if d["project_id"] == proj["project_id"] and d["period"] == period
                    and d["capacity_inclusion_method"] == "authoritative_workload"}
            if not auth and period not in curve_periods:
                continue
            cr = curve_periods.get(period)
            method = next(iter(auth)) if auth else ""
            project_rows.append({
                "project_id": proj["project_id"], "scenario_id": proj["scenario_id"], "project_source": proj["source"],
                "period": period, "curve_phase_keys": "+".join(cr["phase_keys"]) if cr else "",
                "complexity_tier": proj["complexity_tier"], "r1_complexity_profile_id": (r1 or {}).get("complexity_profile_id", "") or "",
                "curve_id": tier["curve_id"], "curve_start_period": proj["curve_start_period"],
                "authoritative_demand_method": method,
                "r1_target_launch_period": (r1["target_launch_date"][:7] if r1 else ""),
                "source_repo": "implementation-operating-system" if r1 else REPO,
                "source_version": inp["standard"]["r1_commit"][:7] if r1 else f"universe-{U['version']}",
                "schema_version": SCHEMA_VERSION})

    # ---- Events ---------------------------------------------------------------------------
    events = []

    def ev(etype, occurred, actor_id, actor_type, subject_type, subject_id, payload):
        events.append({"event_type": etype, "occurred_at": occurred, "actor_id": actor_id, "actor_type": actor_type,
                       "subject_type": subject_type, "subject_id": subject_id, "payload": payload,
                       "source_repo": REPO, "schema_version": std_version})

    for s in sorted(U["scenarios"], key=lambda x: x["selected_at"]):
        ev("org_profile.selected", s["selected_at"], s["selected_by"], "human", "org_profile", s["org_profile_id"], {"org_stage": s["org_stage"]})
    for t in training_cap:
        ev("training_capacity.computed", as_of, t["training_capacity_id"], "system", "training_capacity", t["training_capacity_id"],
           {"period": t["period"], "trainer_hours": jnum(t["trainer_hours"])})
    for g in golive:
        ev("golive_support.computed", as_of, g["golive_support_demand_id"], "system", "golive_support_demand", g["golive_support_demand_id"],
           {"period": g["period"], "project_id": g["project_id"], "support_hours": jnum(g["support_hours"])})
    for s in snapshots:
        ev("capacity.snapshot_computed", as_of, s["capacity_snapshot_id"], "system", "capacity_snapshot", s["capacity_snapshot_id"],
           {"period": s["period"], "demand_hours": jnum(s["demand_hours"]), "supply_hours": jnum(s["effective_capacity_hours"]),
            "capacity_gap_hours": jnum(s["capacity_gap_hours"]), "load_ratio": jnum(s["load_ratio"]), "role_id": s["role_id"]})
    for f, r in zip(fires, recommendations):
        ev("staffing_trigger.fired", as_of, f["rule_id"], "system", "staffing_trigger", f["rule_id"],
           {"period": f["snapshot"]["period"], "rule_id": f["rule_id"], "capacity_gap_hours": jnum(f["snapshot"]["capacity_gap_hours"])})
        ev("staffing_recommendation.recorded", as_of, f["rule_id"], "system", "staffing_recommendation", r["staffing_recommendation_id"],
           {"staffing_trigger_id": f["rule_id"], "status": "proposed"})
    for i, e in enumerate(events, 1):
        e["event_id"] = f"EVT-{i:06d}"

    return {"horizon": horizon, "scenarios": U["scenarios"], "people": U["people"], "projects": project_rows,
            "demand": demand, "training_demand": training_demand, "training_capacity": training_cap, "golive": golive,
            "supply": supply, "role_capacity": role_capacity, "snapshots": snapshots, "recommendations": recommendations,
            "events": events, "skipped_outside_horizon": skipped_outside_horizon, "params": P, "inp": inp}


# --------------------------------------------------------------------------------------
# Output tables
# --------------------------------------------------------------------------------------

TABLES = {
    "scenarios.csv": ("scenarios", ["scenario_id", "label", "org_stage", "org_profile_id", "selected_by", "selected_at", "schema_version"]),
    "people.csv": ("people_rows", ["person_id", "person_label", "scenario_id", "role_id", "scheduled_work_hours", "non_project_hours",
                                   "first_period", "ramp_state", "mentor_of", "unit", "schema_version"]),
    "projects.csv": ("projects", ["project_id", "scenario_id", "project_source", "period", "curve_phase_keys", "complexity_tier",
                                  "r1_complexity_profile_id", "curve_id", "curve_start_period", "authoritative_demand_method",
                                  "r1_target_launch_period", "source_repo", "source_version", "schema_version"]),
    "phase-demand.csv": ("demand", ["demand_record_id", "scenario_id", "project_id", "period", "role_id", "workload_component_id",
                                    "workload_type", "demand_method", "source_entity_type", "source_entity_id", "source_repo",
                                    "source_version", "import_source_repo", "import_record_id", "capacity_inclusion_method",
                                    "precedence_rank", "hours", "actual_hours", "unit", "value_basis", "complexity_tier", "curve_id",
                                    "month_offset", "phase_keys", "exclusion_reason", "schema_version"]),
    "training-demand.csv": ("training_demand_rows", ["training_demand_id", "scenario_id", "project_id", "period", "track_label",
                                                     "learner_count", "class_size", "track_hours", "session_length_hours",
                                                     "prep_hours_per_session", "assessment_hours_per_cohort", "trainer_role_id",
                                                     "capacity_inclusion_method", "covered_by", "source", "schema_version"]),
    "training-capacity.csv": ("training_capacity", ["training_capacity_id", "training_demand_id", "scenario_id", "project_id", "period",
                                                    "trainer_role_id", "learner_count", "class_size", "class_size_source", "track_hours",
                                                    "session_length_hours", "session_length_source", "prep_hours_per_session",
                                                    "prep_source", "assessment_hours_per_cohort", "cohorts_required",
                                                    "sessions_per_cohort", "sessions_required", "trainer_delivery_hours",
                                                    "trainer_preparation_hours", "trainer_assessment_hours", "trainer_hours",
                                                    "learner_seat_hours", "capacity_inclusion_method", "covered_by", "precedence_rank",
                                                    "schema_version"]),
    "golive-support.csv": ("golive", ["golive_support_demand_id", "scenario_id", "project_id", "period", "support_type", "role_id",
                                      "people_count", "hours_per_person_per_day", "days", "support_hours", "capacity_inclusion_method",
                                      "value_basis", "precedence_rank", "schema_version"]),
    "supply-records.csv": ("supply", ["supply_record_id", "scenario_id", "person_id", "role_id", "period", "scheduled_work_hours",
                                      "unavailable_hours", "gross_available_hours", "non_project_hours", "training_hours",
                                      "other_capacity_reduction_hours", "project_available_hours", "ramp_factor", "ramp_adjusted_hours",
                                      "ramp_loss_hours", "mentor_hours", "effective_capacity_hours", "mentor_person_id",
                                      "mentee_person_id", "ramp_source", "value_basis", "unit", "notes", "schema_version"]),
    "role-capacity.csv": ("role_capacity", ["role_capacity_id", "scenario_id", "role_id", "period", "person_count",
                                            "scheduled_work_hours", "unavailable_hours", "gross_available_hours", "non_project_hours",
                                            "training_hours", "other_capacity_reduction_hours", "project_available_hours",
                                            "ramp_loss_hours", "mentor_hours", "effective_capacity_hours", "supply_record_ids",
                                            "schema_version"]),
    "capacity-snapshots.csv": ("snapshots", ["capacity_snapshot_id", "scenario_id", "org_stage", "role_id", "period", "role_capacity_id",
                                             "project_demand_hours", "training_demand_hours", "golive_support_hours", "demand_hours",
                                             "effective_capacity_hours", "capacity_gap_hours", "load_ratio", "load_ratio_state",
                                             "active_project_count", "active_simple_count", "active_standard_count",
                                             "active_complex_count", "max_active_projects_per_role", "concurrency_state",
                                             "active_project_ids", "load_trigger_state", "coverage_trigger_state", "trigger_state",
                                             "active_trigger_ids", "trigger_events", "value_basis", "source_version", "config_digest",
                                             "inputs_digest", "calculation_version", "calculated_at", "standard_version",
                                             "schema_version"]),
    "staffing-recommendations.csv": ("recommendations", ["staffing_recommendation_id", "recommendation_type", "subject_type", "subject_id",
                                                         "content", "source_references", "status", "created_at", "origin_type",
                                                         "origin_id", "staffing_trigger_id", "scenario_id", "role_id", "fired_period",
                                                         "first_affected_period", "capacity_gap_hours", "projected_gap_date",
                                                         "hiring_lead_time_days", "ramp_duration_days", "latest_staffing_start_date",
                                                         "timing_state", "decision_owner", "schema_version"]),
}
EVENT_FIELDS = ["event_id", "event_type", "occurred_at", "actor_id", "actor_type", "subject_type", "subject_id", "payload",
                "source_repo", "schema_version"]


def derived_rows(model: dict) -> dict:
    people_rows = []
    for p in model["people"]:
        ramps = [o for o in p.get("overrides", []) if o["field"] == "ramp_factor" and dec(o["value"]) < 1]
        mentees = sorted({o["mentee"] for o in p.get("overrides", []) if o.get("mentee")})
        for a in p["allocations"]:
            people_rows.append({"person_id": p["person_id"], "person_label": p["label"], "scenario_id": p["scenario_id"],
                                "role_id": a["role_id"], "scheduled_work_hours": a["scheduled_work_hours"],
                                "non_project_hours": a["non_project_hours"], "first_period": p.get("first_period", model["horizon"][0]),
                                "ramp_state": "ramping" if any(o["role_id"] == a["role_id"] for o in ramps) else "fully_ramped",
                                "mentor_of": ";".join(mentees), "unit": "hours", "schema_version": SCHEMA_VERSION})
    trd = [{**t, "project_id": t["project_id"] or "", "covered_by": t.get("covered_by") or "", "source": "r4_interface_fixture",
            "schema_version": SCHEMA_VERSION} for t in model["training_demand"]]
    return {"people_rows": people_rows, "training_demand_rows": trd,
            "scenarios": [{**s, "schema_version": SCHEMA_VERSION} for s in model["scenarios"]]}


def cell(v) -> str:
    if v is None:
        return ""
    if isinstance(v, (list, dict)):
        return json.dumps(v, sort_keys=True, separators=(",", ":"))
    if isinstance(v, (int, float, Decimal, bool)):
        return fmt(v)
    return str(v)


def render_csv(rows: list[dict], fields: list[str]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(fields)
    for r in rows:
        w.writerow([cell(r.get(f)) for f in fields])
    return buf.getvalue()


def render_events(events: list[dict]) -> str:
    return "".join(json.dumps({k: e[k] for k in EVENT_FIELDS}, separators=(",", ":")) + "\n" for e in events)


# --------------------------------------------------------------------------------------
# Generated documents
# --------------------------------------------------------------------------------------

ROLE_NAMES = {"ROL-000001": "implementation lead", "ROL-000004": "technical specialist",
              "ROL-000005": "enablement lead", "ROL-000006": "support owner"}


def md_table(header: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(cell(c) if not isinstance(c, str) else c for c in r) + " |" for r in rows]
    return "\n".join(out)


def ratio_text(s: dict) -> str:
    return fmt(s["load_ratio"]) if s["load_ratio_state"] == "defined" else "undefined_no_capacity"


def generated_header(title: str) -> str:
    return (f"# {title}\n\n<!-- Generated by tools/capacity_calc.py. Do not edit by hand; edit the inputs and rerun. -->\n\n")


def doc_capacity_summary(m: dict) -> str:
    out = generated_header("Capacity summary")
    out += ("Purpose: one table per scenario showing, for each role and month, the demand hours, the effective capacity "
            "hours, the capacity gap (demand minus supply; positive means more work than capacity), and the load ratio. "
            "Use it to see where demand is greater than supply before a monthly review.\n\n")
    out += "Reading the table: a gap of 0 or less means the planned work fits. `undefined_no_capacity` means the role has demand or a slot but zero effective hours, so no ratio is calculated.\n\n"
    for sc in m["scenarios"]:
        snaps = [s for s in m["snapshots"] if s["scenario_id"] == sc["scenario_id"]]
        out += f"## {sc['label']} ({sc['scenario_id']}, {sc['org_stage']})\n\n"
        rows = [[s["period"], s["role_id"], ROLE_NAMES.get(s["role_id"], ""), s["demand_hours"], s["effective_capacity_hours"],
                 s["capacity_gap_hours"], ratio_text(s), s["trigger_state"]] for s in snaps]
        out += md_table(["Period", "Role", "Role name", "Demand hours", "Effective capacity hours", "Gap hours", "Load ratio", "Trigger state"], rows) + "\n\n"
    out += f"{SYNTHETIC_FOOTER}\n"
    return out


def doc_demand_vs_supply(m: dict) -> str:
    out = generated_header("Demand vs supply")
    out += ("Purpose: show where demand comes from (project work, training delivery, launch support) and why supply is "
            "what it is (every named allowance in hours). This is the drill-down behind the capacity summary.\n\n")
    out += "## Demand by source, all roles, per scenario and month\n\n"
    rows = []
    for sc in m["scenarios"]:
        for p in m["horizon"]:
            snaps = [s for s in m["snapshots"] if s["scenario_id"] == sc["scenario_id"] and s["period"] == p]
            bu = sum((d["hours"] for d in m["demand"] if d["scenario_id"] == sc["scenario_id"] and d["period"] == p
                      and d["capacity_inclusion_method"] == "authoritative_workload" and d["demand_method"] == "bottom_up"), D(0))
            td = sum((d["hours"] for d in m["demand"] if d["scenario_id"] == sc["scenario_id"] and d["period"] == p
                      and d["capacity_inclusion_method"] == "authoritative_workload" and d["demand_method"] == "top_down"), D(0))
            tr = sum((s["training_demand_hours"] for s in snaps), D(0))
            gl = sum((s["golive_support_hours"] for s in snaps), D(0))
            tot = sum((s["demand_hours"] for s in snaps), D(0))
            sup = sum((s["effective_capacity_hours"] for s in snaps), D(0))
            rows.append([sc["scenario_id"], p, bu, td, tr, gl, tot, sup, tot - sup])
    out += md_table(["Scenario", "Period", "Bottom-up project hours", "Top-down project hours", "Trainer hours", "Launch-support hours",
                     "Demand hours", "Effective capacity hours", "Gap hours"], rows) + "\n\n"
    out += "## Supply allowances, all roles, per scenario and month\n\n"
    rows = []
    for sc in m["scenarios"]:
        for p in m["horizon"]:
            rcs = [r for r in m["role_capacity"] if r["scenario_id"] == sc["scenario_id"] and r["period"] == p]
            def s(f):
                return sum((r[f] for r in rcs), D(0))
            rows.append([sc["scenario_id"], p, s("scheduled_work_hours"), s("unavailable_hours"), s("non_project_hours"),
                         s("training_hours"), s("ramp_loss_hours"), s("mentor_hours"), s("effective_capacity_hours")])
    out += md_table(["Scenario", "Period", "Scheduled", "Unavailable", "Non-project", "Own training", "Ramp loss", "Mentoring", "Effective capacity"], rows) + "\n\n"
    out += f"{SYNTHETIC_FOOTER}\n"
    return out


def doc_staffing_signals(m: dict) -> str:
    out = generated_header("Staffing signals")
    out += ("Purpose: list every staffing trigger that fired and the proposed recommendation it produced. A trigger means "
            "operational conditions justify a staffing conversation. It never means hire someone, and every recommendation "
            "stays `proposed` until a named person decides.\n\n")
    out += "## Recommendations\n\n"
    rows = [[r["staffing_recommendation_id"], r["scenario_id"], r["role_id"], r["staffing_trigger_id"], r["recommendation_type"],
             r["first_affected_period"], r["fired_period"], r["capacity_gap_hours"], r["latest_staffing_start_date"], r["timing_state"],
             r["status"]] for r in m["recommendations"]]
    out += md_table(["ID", "Scenario", "Role", "Rule", "Type", "First affected", "Fired", "Gap hours at firing",
                     "Latest staffing start", "Timing", "Status"], rows) + "\n\n"
    out += "## Trigger state changes\n\n"
    rows = [[s["capacity_snapshot_id"], s["scenario_id"], s["role_id"], s["period"], ratio_text(s), s["trigger_events"]]
            for s in m["snapshots"] if s["trigger_events"]]
    out += md_table(["Snapshot", "Scenario", "Role", "Period", "Load ratio", "Events"], rows) + "\n\n"
    out += "## Watch periods (above the threshold, not yet persistent)\n\n"
    rows = [[s["capacity_snapshot_id"], s["scenario_id"], s["role_id"], s["period"], ratio_text(s)]
            for s in m["snapshots"] if "watch" in (s["load_trigger_state"], s["coverage_trigger_state"])]
    out += (md_table(["Snapshot", "Scenario", "Role", "Period", "Load ratio"], rows) if rows else "None.") + "\n\n"
    out += "## Concurrency observations\n\n"
    rows = [[s["capacity_snapshot_id"], s["scenario_id"], s["role_id"], s["period"], s["active_project_count"],
             s["max_active_projects_per_role"]] for s in m["snapshots"] if s["concurrency_state"] == "above_configured_maximum"]
    out += (md_table(["Snapshot", "Scenario", "Role", "Period", "Active projects", "Configured maximum"], rows) if rows else "None.") + "\n\n"
    out += "The configured maximum comes from the selected organization profile. It is a user-configurable parameter and a proposed design value, not a measured result; it is an observation threshold, never a benchmark.\n\n"
    out += f"{SYNTHETIC_FOOTER}\n"
    return out


def doc_training_support(m: dict) -> str:
    out = generated_header("Training and launch support")
    out += ("Purpose: show how much implementation capacity training delivery and launch support consume. Learner "
            "seat-hours describe the learners' time and are shown only for context; they are never trainer workload.\n\n")
    out += "## Training capacity\n\n"
    rows = [[t["training_capacity_id"], t["training_demand_id"], t["scenario_id"], t["period"], t["trainer_role_id"], t["learner_count"],
             t["class_size"], t["cohorts_required"], t["sessions_required"], t["trainer_delivery_hours"], t["trainer_preparation_hours"],
             t["trainer_assessment_hours"], t["trainer_hours"], t["learner_seat_hours"], t["capacity_inclusion_method"]] for t in m["training_capacity"]]
    out += md_table(["TRC", "TRD", "Scenario", "Period", "Trainer role", "Learners", "Class size", "Cohorts", "Sessions",
                     "Delivery h", "Prep h", "Assessment h", "Trainer h", "Learner seat-h (not workload)", "Inclusion"], rows) + "\n\n"
    out += "## Launch support\n\n"
    rows = [[g["golive_support_demand_id"], g["scenario_id"], g["project_id"], g["period"], g["support_type"], g["role_id"],
             g["people_count"], g["hours_per_person_per_day"], g["days"], g["support_hours"]] for g in m["golive"]]
    out += md_table(["GLS", "Scenario", "Project", "Period", "Type", "Role", "People", "Hours per person per day", "Days", "Support hours"], rows) + "\n\n"
    out += "Launch-support hours plan workload on the assumption that each launch proceeds as planned in R1. R2 records no readiness, gate, or go or no-go decision.\n\n"
    out += f"{SYNTHETIC_FOOTER}\n"
    return out


def doc_operating_review(m: dict) -> str:
    out = generated_header("Operating review")
    out += ("Purpose: a one-page agenda for a monthly capacity conversation, built from the other four reports. Every line "
            "is a deterministic count or value; nothing here is an AI narrative or a decision.\n\n")
    snaps = m["snapshots"]
    out += "## This month at a glance\n\n"
    rows = []
    for sc in m["scenarios"]:
        ss = [s for s in snaps if s["scenario_id"] == sc["scenario_id"]]
        rows.append([sc["scenario_id"], sc["org_stage"], len(ss), sum(1 for s in ss if s["capacity_gap_hours"] > 0),
                     sum(1 for s in ss if s["load_ratio_state"] == "undefined_no_capacity"),
                     sum(1 for s in ss if s["trigger_state"] in ("triggered", "clearing")),
                     sum(1 for r in m["recommendations"] if r["scenario_id"] == sc["scenario_id"])])
    out += md_table(["Scenario", "Selected stage", "Role-months", "Role-months with demand above supply",
                     "Role-months with zero capacity", "Role-months with an active trigger", "Proposed recommendations"], rows) + "\n\n"
    out += "## Questions for the review\n\n"
    out += ("1. Are the forecast projects and their complexity tiers still right? (Top-down demand is only as good as the forecast.)\n"
            "2. For each proposed recommendation, who is the named person who decides, and by when?\n"
            "3. Where a timing window has passed, what is the fallback: rebalance, role mix, or a changed launch plan in R1?\n"
            "4. Do any concurrency observations suggest reviewing the selected organization stage? (A person decides; R2 never changes it.)\n"
            "5. Which source or double-count warnings in `verification/source-precedence-check.md` need an upstream fix in R1 or R3?\n\n")
    out += "## Decisions\n\nRecorded by the named person after the review, outside R2. R2 records no decision.\n\n"
    out += f"{SYNTHETIC_FOOTER}\n"
    return out


def doc_source_precedence(m: dict) -> str:
    out = generated_header("Source-precedence check")
    out += ("This file is regenerated on every run. It proves, from the generated records, that each project and period "
            "has at most one authoritative demand method and each workload component is authoritative at most once.\n\n")
    dem = m["demand"]
    counts = defaultdict(int)
    for d in dem:
        counts[(d["demand_method"], d["capacity_inclusion_method"])] += 1
    rows = [[k[0], k[1], v, fmt(sum((d["hours"] for d in dem if (d["demand_method"], d["capacity_inclusion_method"]) == k), D(0)))]
            for k, v in sorted(counts.items())]
    out += "## Demand records by method and inclusion\n\n" + md_table(["Method", "Inclusion", "Records", "Hours"], rows) + "\n\n"
    keys = defaultdict(set)
    for d in dem:
        if d["capacity_inclusion_method"] == "authoritative_workload":
            keys[(d["project_id"], d["period"])].add(d["demand_method"])
    both = defaultdict(set)
    for d in dem:
        both[(d["project_id"], d["period"])].add(d["demand_method"])
    rows = [[p, per, ", ".join(sorted(both[(p, per)])), ", ".join(sorted(keys[(p, per)]))] for (p, per) in sorted(both) if len(both[(p, per)]) > 1]
    out += "## Project-periods with records from both methods\n\n"
    out += "Each row shows that only one method stays authoritative.\n\n"
    out += md_table(["Project", "Period", "Methods present", "Authoritative method"], rows) + "\n\n"
    probs = double_count_problems(dem)
    out += f"## Result\n\n- Project-periods with authoritative demand: {len(keys)}\n- Project-periods with more than one authoritative method: {sum(1 for v in keys.values() if len(v) > 1)}\n"
    out += f"- Components authoritative more than once in a period: {sum(1 for p in probs if 'authoritative more than once' in p)}\n"
    out += f"- R3 Capacity Inputs rows outside the planning horizon, not imported: {len(m['skipped_outside_horizon'])}\n"
    excl = [t for t in m["training_capacity"] if t["capacity_inclusion_method"] != "authoritative_workload"]
    out += f"- Training records excluded to prevent double counting: {len(excl)} ({', '.join(t['training_demand_id'] + ' covered by ' + t['covered_by'] for t in excl)})\n"
    out += f"- Double-count problems: {len(probs)}\n\n"
    out += f"{SYNTHETIC_FOOTER}\n"
    return out


def doc_synthetic_check(m: dict, outputs: dict) -> str:
    out = generated_header("Synthetic dataset check")
    out += "Exact row counts of every generated synthetic file (header excluded). These counts are locked by `tests/test_outputs.py`.\n\n"
    rows = []
    for name in sorted(outputs):
        if name.startswith("data/synthetic/") and name.endswith((".csv", ".jsonl")):
            n = outputs[name].count("\n") - (1 if name.endswith(".csv") else 0)
            rows.append([f"`{name}`", n])
    out += md_table(["File", "Rows"], rows) + "\n\n"
    out += "## Demonstration coverage\n\n"
    snaps = m["snapshots"]
    checks = [
        ("Spare capacity (gap below 0)", sum(1 for s in snaps if s["capacity_gap_hours"] < 0)),
        ("Near balance (defined load ratio from 0.95 to 1.05)", sum(1 for s in snaps if s["load_ratio_state"] == "defined" and D("0.95") <= s["load_ratio"] <= D("1.05"))),
        ("Demand above supply (gap above 0)", sum(1 for s in snaps if s["capacity_gap_hours"] > 0)),
        ("Zero effective capacity", sum(1 for s in snaps if s["effective_capacity_hours"] == 0)),
        ("Ramp effect (supply records with ramp loss)", sum(1 for s in m["supply"] if s["ramp_loss_hours"] > 0)),
        ("Mentor load (supply records with mentor hours)", sum(1 for s in m["supply"] if s["mentor_hours"] > 0)),
        ("Part-period availability (supply records with unavailable hours)", sum(1 for s in m["supply"] if s["unavailable_hours"] > 0)),
        ("Person holding more than one role", len({p["person_id"] for p in m["people"] if len(p["allocations"]) > 1})),
        ("Trigger fired", sum(1 for s in snaps if "fired" in s["trigger_events"])),
        ("Trigger cleared", sum(1 for s in snaps if "cleared" in s["trigger_events"])),
        ("Watch period (above, not yet persistent)", sum(1 for s in snaps if "watch" in (s["load_trigger_state"], s["coverage_trigger_state"]))),
        ("Concurrency above the configured maximum", sum(1 for s in snaps if s["concurrency_state"] == "above_configured_maximum")),
        ("Training defaults applied", sum(1 for t in m["training_capacity"] if "default_parameter" in (t["class_size_source"], t["session_length_source"], t["prep_source"]))),
    ]
    out += md_table(["Demonstrated state", "Count"], [[a, b] for a, b in checks]) + "\n\n"
    out += f"{SYNTHETIC_FOOTER}\n"
    return out


def doc_formula_audit(m: dict) -> str:
    out = generated_header("Formula audit")
    out += ("Each line recomputes one formula from its raw inputs, independently of the stored value, and compares. "
            "`tools/validate.py` runs the same comparisons on every record; this file shows one traced example per "
            "formula plus the totals.\n\n")
    P = m["params"]
    snaps = m["snapshots"]
    trace = max((s for s in snaps if s["load_ratio_state"] == "defined"), key=lambda s: (s["capacity_gap_hours"], s["capacity_snapshot_id"]))
    out += f"## Trace: why did {trace['capacity_snapshot_id']} show a {fmt(trace['capacity_gap_hours'])}-hour gap?\n\n"
    out += f"Scenario {trace['scenario_id']}, role {trace['role_id']}, period {trace['period']}.\n\n"
    src = trace["_digest_src"]
    out += "Demand inputs (authoritative only):\n\n"
    rows = [[i, h] for i, h in src["demand_records"]] + [[i, h] for i, h in src["training_capacity"]] + [[i, h] for i, h in src["golive_support"]]
    out += md_table(["Record", "Hours"], rows) + "\n\n"
    out += "Supply inputs:\n\n" + md_table(["Supply record", "Effective capacity hours"], [[i, h] for i, h in src["supply_records"]]) + "\n\n"
    out += (f"demand_hours = {fmt(trace['demand_hours'])}; effective_capacity_hours = {fmt(trace['effective_capacity_hours'])}; "
            f"capacity_gap_hours = {fmt(trace['demand_hours'])} - {fmt(trace['effective_capacity_hours'])} = {fmt(trace['capacity_gap_hours'])}; "
            f"load_ratio = {ratio_text(trace)}.\n\n")
    out += f"inputs_digest `{trace['inputs_digest']}` is the SHA-256 of exactly these record IDs and hours plus config digest `{trace['config_digest'][:12]}...`, calculation version {trace['calculation_version']}, and standard version {trace['standard_version']}.\n\n"
    out += "## Totals recomputed\n\n"
    rows = [
        ["Authoritative demand records", sum(1 for d in m["demand"] if d["capacity_inclusion_method"] == "authoritative_workload")],
        ["Sum of snapshot demand_hours", sum((s["demand_hours"] for s in snaps), D(0))],
        ["Sum of authoritative project, trainer, and launch-support hours",
         sum((d["hours"] for d in m["demand"] if d["capacity_inclusion_method"] == "authoritative_workload"), D(0))
         + sum((t["trainer_hours"] for t in m["training_capacity"] if t["capacity_inclusion_method"] == "authoritative_workload"), D(0))
         + sum((g["support_hours"] for g in m["golive"]), D(0))],
        ["Sum of snapshot effective_capacity_hours", sum((s["effective_capacity_hours"] for s in snaps), D(0))],
        ["Sum of supply-record effective_capacity_hours", sum((s["effective_capacity_hours"] for s in m["supply"]), D(0))],
        ["Learner seat-hours (never in demand)", sum((t["learner_seat_hours"] for t in m["training_capacity"]), D(0))],
    ]
    out += md_table(["Check", "Value"], rows) + "\n\n"
    out += "## Parameters used\n\n"
    keys = ["load_ratio_upper_threshold", "load_ratio_lower_threshold", "trigger_fire_after_periods", "trigger_clear_after_periods",
            "coverage_fire_after_periods", "coverage_clear_after_periods", "hiring_lead_time_days", "ramp_duration_days",
            "default_class_size", "default_session_length_hours", "default_prep_hours_per_session"]
    out += md_table(["Parameter", "Value"], [[k, cell(P[k])] for k in keys]) + "\n\n"
    out += "Every value above is a user-configurable parameter and a proposed design value, not a measured result.\n\n"
    out += f"{SYNTHETIC_FOOTER}\n"
    return out


def build_outputs(model: dict) -> dict[str, str]:
    rows = {**model, **derived_rows(model)}
    out = {}
    for name, (key, fields) in TABLES.items():
        out[f"data/synthetic/{name}"] = render_csv(rows[key], fields)
    out["data/synthetic/events.jsonl"] = render_events(model["events"])
    out["reports/executive-pack/capacity-summary.md"] = doc_capacity_summary(model)
    out["reports/executive-pack/demand-vs-supply.md"] = doc_demand_vs_supply(model)
    out["reports/executive-pack/staffing-signals.md"] = doc_staffing_signals(model)
    out["reports/executive-pack/training-support.md"] = doc_training_support(model)
    out["reports/executive-pack/operating-review.md"] = doc_operating_review(model)
    out["verification/source-precedence-check.md"] = doc_source_precedence(model)
    out["verification/formula-audit.md"] = doc_formula_audit(model)
    out["verification/synthetic-data-check.md"] = doc_synthetic_check(model, out)
    return out


def run(root: Path = ROOT, check: bool = False) -> int:
    model = compute(load_inputs(root))
    outputs = build_outputs(model)
    stale = []
    for rel, text in outputs.items():
        path = root / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(rel)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(text.encode("utf-8"))
    if check:
        for rel in stale:
            print(f"STALE {rel}")
        print(f"{len(outputs)} generated files; {len(stale)} differ from the calculator")
        return 1 if stale else 0
    print(f"{len(outputs)} generated files; {len(stale)} rewritten")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="R2 reference capacity calculator.")
    ap.add_argument("--root", default=str(ROOT))
    ap.add_argument("--check", action="store_true", help="exit 1 if any committed output differs")
    a = ap.parse_args(argv)
    return run(Path(a.root).resolve(), a.check)


if __name__ == "__main__":
    sys.exit(main())
