"""Copy the upstream files R2 reads from R1 and R3 at exact, named commits.

R2 never reads "latest". This tool copies each listed file byte for byte from a local
clone at the commit named on the command line, writes `upstream/manifest.yaml` with a
SHA-256 for every copy, and writes `standard/standard-reference.yaml`. The validator
fails if any copy stops matching its manifest hash.

Usage:
    python tools/sync_upstream.py --r1-repo PATH --r1-commit SHA40 --r3-repo PATH --r3-commit SHA40

Exit codes: 0 written, 2 refused (missing clone, short or symbolic commit, missing file).
"""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

R1_NAME = "implementation-operating-system"
R3_NAME = "implementation-tracker-workbook"
R1_VERSION = "0.1.0"
R3_VERSION = "0.1.0"
STANDARD_VERSION = "1.0.0"

# R1 files: the shared standard contracts R2 must obey, plus the synthetic records R2
# references (projects, tasks, roles). R2 reads them; it never changes them.
R1_FILES = (
    "standard/id-registry.yaml",
    "standard/event-catalog.yaml",
    "standard/status-vocabularies.yaml",
    "standard/org-stages.yaml",
    "standard/glossary.md",
    "standard/label-rules.yaml",
    "standard/lifecycle-terms.yaml",
    "standard/schemas/event.schema.json",
    "standard/schemas/recommendation.schema.json",
    "data/synthetic/projects.csv",
    "data/synthetic/tasks.csv",
    "data/synthetic/README.md",
)
# R3 files: the Capacity Inputs export and its contract. R2 consumes the rows and may not
# redefine their meaning.
R3_FILES = (
    "exports/csv/capacity-inputs.csv",
    "schemas/r3/capacity-input.schema.json",
)
FULL_SHA = re.compile(r"^[0-9a-f]{40}$")


def git_show(repo: Path, commit: str, path: str) -> bytes:
    result = subprocess.run(["git", "-C", str(repo), "show", f"{commit}:{path}"], capture_output=True, check=False)
    if result.returncode != 0:
        raise SystemExit(f"refused: {path} not found at {commit[:7]} in {repo}")
    return result.stdout


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--r1-repo", required=True)
    parser.add_argument("--r1-commit", required=True)
    parser.add_argument("--r3-repo", required=True)
    parser.add_argument("--r3-commit", required=True)
    args = parser.parse_args(argv)
    for name, commit in (("--r1-commit", args.r1_commit), ("--r3-commit", args.r3_commit)):
        if not FULL_SHA.match(commit):
            print(f"refused: {name} must be a full 40-character commit, not a branch, tag, or 'latest'", file=sys.stderr)
            return 2
    entries = []
    for repo_name, repo, commit, files, local_root in (
        (R1_NAME, Path(args.r1_repo), args.r1_commit, R1_FILES, "upstream/r1"),
        (R3_NAME, Path(args.r3_repo), args.r3_commit, R3_FILES, "upstream/r3"),
    ):
        if not (repo / ".git").exists():
            print(f"refused: {repo} is not a git clone", file=sys.stderr)
            return 2
        for path in files:
            data = git_show(repo, commit, path)
            target = ROOT / local_root / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
            entries.append((repo_name, commit, path, f"{local_root}/{path}", hashlib.sha256(data).hexdigest()))

    lines = [
        "# Generated by tools/sync_upstream.py. Do not edit by hand.",
        "# Each file below is a byte-identical copy of an upstream file at the pinned commit.",
        "# tools/validate.py fails if a copy's SHA-256 differs from this manifest.",
        "files:",
    ]
    for repo_name, commit, path, local, digest in entries:
        lines += [
            f"- source_repo: {repo_name}",
            f"  source_commit: {commit}",
            f"  source_path: {path}",
            f"  local_path: {local}",
            f"  sha256: {digest}",
        ]
    (ROOT / "upstream" / "manifest.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    reference = f"""# Generated by tools/sync_upstream.py. Do not edit by hand.
# The upstream versions this repository is built and validated against.
shared_standard_version: {STANDARD_VERSION}
shared_standard_repo: {R1_NAME}
r1_repo: {R1_NAME}
r1_version: {R1_VERSION}
r1_tag: v{R1_VERSION}
r1_commit: {args.r1_commit}
r3_repo: {R3_NAME}
r3_version: {R3_VERSION}
r3_tag: v{R3_VERSION}
r3_commit: {args.r3_commit}
manifest: upstream/manifest.yaml
pinned_files: {len(entries)}
authority: >-
  R1 and shared standard 1.0.0 own shared vocabulary, IDs, events, projects, tasks, and
  roles. R3 owns the Capacity Inputs export shape and meaning. R2 consumes both and owns
  only demand, supply, capacity, staffing signals, organization-stage planning, training
  and launch-support capacity.
"""
    (ROOT / "standard" / "standard-reference.yaml").write_text(reference, encoding="utf-8")
    print(f"pinned {len(entries)} upstream files (R1 {args.r1_commit[:7]}, R3 {args.r3_commit[:7]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
